version: "3.1"
services:
  browser:
    image: selenium/standalone-chrome
    container_name: browser
    ports:
      - "4444:4444"
  map:
    build: .
    container_name: map
    working_dir: /app
    volumes:
      - ./src:/app
      - ./data:/data